title: RevolutionUC Spring 2018
description: "Student Hackathon held at the University of Cincinnati - March 3rd and 4th, 2017"

sass:
  sass_dir: _scss
  style: :compressed

# items to exclude from the build
exclude: ["README.md", "Gemfile", "Gemfile.lock", "README.md"]
